export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const CLEAR_LOGIN_ERRORS = "CLEAR_LOGIN_ERRORS";

export const LOGOUT = "LOGOUT";
